image: "python:3.7"

stages:
    - deploy

publish:
  stage: deploy
  image: 
    name: ubuntu
    entrypoint: [""]
  services:
    - docker:dind
  before_script:
    - apt-get update
    - apt-get install -y  python3 python3-pip
    - pip3 install databricks-cli --upgrade
  script:
    - chmod 777 setup_datalake.sh
    - ./setup_datalake.sh
