image: "python:3.7"

stages:
    - deploy





except-pull-requests:
  script: echo 'this should not run on pull requests'
  except:
    - external_pull_requests
publish:
  only:
    - main
  stage: deploy
  image: 
    name: ubuntu
    entrypoint: [""]
  services:
    - docker:dind
  before_script:
    - apt-get update
    - apt-get install -y  python3 python3-pip
    - pip3 install databricks-cli --upgrade
    #- echo '{}' > ~/.databricks-connect
  script:
    - 
